### ISSUE TITLE
Feature Request: Break x86 and x64 software source folders into separate folders

### ISSUE THREAD

**Issue by josephreynolds1** [asjimene/CMPackager#101]
Current x86 and x64 packages are downloaded into the same source folder for the package.  Create x86/x64 or x32/64 folders instead and put corresponding source files in each.  Then have the individual deployment types for each processor architecture reference the processor type sub folder.  This would reduce the size of the deployment package that has to be downloaded.

**Current:**

![image](https://user-images.githubusercontent.com/46980014/117879644-32e94c00-b275-11eb-9ec7-11037ec9fd80.png)

**Proposed:**

![image](https://user-images.githubusercontent.com/46980014/117879951-8bb8e480-b275-11eb-8906-740390a86bef.png)

**Comment by asjimene** [comment]
This is actually a per-recipe setting <AppRepoFolder> will do this: https://github.com/asjimene/CMPackager/blob/master/Recipes/Template.xml#L63
