### ISSUE TITLE
Copy Paste Applications

### ISSUE THREAD

**Issue by armss001** [asjimene/CMPackager#118]
Hello, 

Is it possible to use this to package applications with no download, but instead use 2 copy commands to merge a settings file and install script with the latest build contents? 

For example 

C:\InstallerTemplates\Application1
C:\Builds\Application1\10.1.32.12\

In this instance the build is taken, merged with PSADT and the script package is built.

**Comment by theaquamarine** [comment]
You could not include a url in the recipe (so it has nothing to download) and do the actual work in the prefetch script, the Configmgr Console and Support Center recipes do something along these lines.

For the combining two sources, it might work to use one as downloadfile and copy the second in using extracopyfunctions. I think the git recipe can copy a git.inf file so might help as an example.
________________________________
From: armss001 ***@***.***>
Sent: Thursday, March 10, 2022 9:12:51 AM
To: asjimene/CMPackager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [asjimene/CMPackager] Copy Paste Applications (Issue #118)


Hello,

Is it possible to use this to package applications with no download, but instead use 2 copy commands to merge a settings file and install script with the latest build contents?

For example

C:\InstallerTemplates\Application1
C:\Builds\Application1\10.1.32.12\

In this instance the build is taken, merged with PSADT and the script package is built.

**Comment by armss001** [comment]
I am running into a $null value error, But I am looking and that could be from elsewhere. I think my logic for finding the latest build was Broken. 

Is there away I can use a PowerShell Script to build the detection logic? I only see built in methods. 

Thanks, for the quick response

**Comment by theaquamarine** [comment]
Yeah, one of the DetectionMethodTypes is CustomScript, which is the equivalent of the script option on the detection method page of an application's properties. Off the top of my head, I think the sysmon and powerbi recipes use it.
________________________________

**Comment by rjohnson06gh** [comment]
We've done this for several applications to make a "local" autopackager application in instances where the download is behind a login and we cannot send it credentials well enough or we need to stay at a specific version. We continue to use the mechanisms built into CMPackager, but treat the network share as the "website".  I've attached one example where I've stripped off our server path. We use install and uninstall batch wrappers for some installs, and this application is one of them and we put the files into the ExtraFiles location, so maybe that's where your extra config files could go.

I've attached two examples: one where it's just a local packaging example. The other does a web version check (this example is behind a login, but the version is publicly accessible), and sends a Teams notification that a new version is available for download.
[Minitab-Local.txt](https://github.com/asjimene/CMPackager/files/8225249/Minitab-Local.txt)
[AfterMath-Local-WebVersionCheck.txt](https://github.com/asjimene/CMPackager/files/8225250/AfterMath-Local-WebVersionCheck.txt)

**Comment by armss001** [comment]
Thanks, I was able to get it working, turns out I was setting the wrong Var. 
$Version needed to be $Download.Version.

I found it in the script, but now it all works as intended just using the Copy scripting, and prefetching the version build. But now we may look to add a download anyway and pull the latest PSADT.
