### ISSUE TITLE
Error processing Notepad++.xml

### ISSUE THREAD

**Issue by inforishikapoor7** [asjimene/CMPackager#120]
I am getting the error message below for whatever recipe I am trying to use from your CMpackager script. Any insight will be appreciated.

Error processing Notepad++.xml: Object reference not set to an instance of an object. at Start-ApplicationDownload, C:\Temp\Main\CMPackager-main\CMPackager.ps1: line 533
at <ScriptBlock><Process>, C:\Temp\Main\CMPackager-main\CMPackager.ps1: line 2081

**Comment by asjimene** [comment]
Should be fixed with #130
