### ISSUE TITLE
Create additional application deployments (available/required)

### ISSUE THREAD

**Issue by TheTaran** [asjimene/CMPackager#128]
Is there a possibility to set 2 different deployments for one application with the CMPackager script?
For example:

Application A deployment required for collection A (Collection with already installed application)
Application A deployment available for collection B (collection with all systems, for user installation with software center)

I have tried to set up 2 different CMPackager scripts, one setting available and the other setting required deployments.
But as soon as one of the two scripts deploys the first application in sccm, the second script does not perform any additional deployment.

**Comment by ItsThatDude** [comment]
This already works - You just need to create more Deployment entries in the one recipe

	<Deployment>
		<DeploySoftware>True</DeploySoftware>
		<DeploymentCollection Purpose="Required">Collection A</DeploymentCollection>
		<DeploymentCollection>Collection B</DeploymentCollection>
	</Deployment>
