### ISSUE TITLE
Issue with AdobeReader Recipe

### ISSUE THREAD

**Issue by chrisafric** [asjimene/CMPackager#131]
Hi, 

I would just like to seek your assistance regarding the reciper for Adobe Reader please.

Please correct me if I'm wrong and if this is something that can be corrected. The version of my cmpackager was Created on:   	1/9/2018 11:34 AM

There are two issues that I have discovered:

1. It downloads Adobe Reader and packages it on SCCM however I noticed that the bathfiles that it creates only contains the command "Setup.exe" which I believe is not correct. Please see screenshot below.

![image](https://user-images.githubusercontent.com/118394625/217989748-92544041-b759-4e9c-aac2-ff2b5b1517bf.png)

2. Second issue I discovered was that the detection method it uses is incorrect. For some reason, the detection of the product code/key of the Adobe Reader I downloaded today 10th Feb 2023 is the same product code/key I downloaded9th March 2022.

see screenshots below from version 22.1.20085 

![image](https://user-images.githubusercontent.com/118394625/217990921-d8021878-820d-40ee-b1fb-5b7929bcba00.png)

Version: 22.3.20314

![image](https://user-images.githubusercontent.com/118394625/217990953-bfa3741d-e3e6-4a09-b0d6-dd8752aab25f.png)

regards,
CA

**Comment by asjimene** [comment]
Hmm, I am checking in on this. It is supposed to add a file rule for the detection.
