### ISSUE TITLE
Some Recipes not downloading the Application (Deployment Type)

### ISSUE THREAD

**Issue by chrisafric** [asjimene/CMPackager#136]
Hi asjimene,

Good day!

just wanted to seek your assistance regarding some recipes I am having issues with please.

I have some recipes which I grabbed here and for some reason some of them are not downloading the Application from the website. These are:
1. Notepad++
2. iTunes
3. Google Chrome
4. Adobe Acrobat Reader DC
5. File Zilla

The only working recipe that I have is **Microsoft Power BI.**

I have attached the notepad text when I ran the app.
[cmpackager-notepad.txt](https://github.com/asjimene/CMPackager/files/11875163/cmpackager-notepad.txt)

regards,
CA

**Comment by asjimene** [comment]
I'm going to guess this was some sort of firewall or similar?

**Comment by chrisafric** [comment]
Hi,

Yes I can confirm that it was blocked because the URL to download PowerBI worked by entering the URL manually while the rest was page cant be displayed.

Thanks for Checking.

regards,
CA
________________________________
