### ISSUE TITLE
Feature - Allow Automatic Supersedence

### ISSUE THREAD

**Issue by asjimene** [asjimene/CMPackager#20]
Allow newly packaged applications to supersede the previously packaged version automatically.  This should be configurable per app.

**Comment by KA-RJO** [comment]
Hello. Do you have a plan for fixing this issue? We are still waiting for just this feature to implement your solution in our environment. Also, great work!!

**Comment by asjimene** [comment]
I am still planning on adding this feature, but I have been swamped with a new job and upcoming speaking engagements.
