### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DavidMcSpadden** [asjimene/CMPackager#22]
Trying to get this to work but it does nothing?

<ApplicationDef>
	<Application>
		<Name>Mozilla Firefox</Name>
		<Description>The Firefox Edition is a version of Firefox that's tailored for web users. It includes: the latest Firefox features. Each new release includes features which have been stabilized via nightly builds. Free Software.</Description>
		<Publisher>Mozilla</Publisher>
		<AutoInstall>True</AutoInstall>
		<UserDocumentation>https://support.mozilla.org/en-US/products/firefox?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=nav&utm_content=firefox</UserDocumentation>
		<Icon>FirefoxDev.ico</Icon>
	</Application>
	<Downloads>
		<Download DeploymentType="DeploymentType1">
			<PrefetchScript>
				Function Get-RedirectedUrl 
					{
					Param 	(
						[Parameter(Mandatory=$true)]
						[String]$URL
					)
					$request = [System.Net.WebRequest]::Create($url)
					$request.AllowAutoRedirect=$false
					$response=$request.GetResponse()
					If ($response.StatusCode -eq "Found")
						{
						$response.GetResponseHeader("Location")
						}
					}

				$FileName = ([System.IO.Path]::GetFileName((Get-RedirectedUrl "https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US"))).replace("%20"," ") 
				Invoke-WebRequest -uri "https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US" -Outfile "$TempDir\$FileName"
				$LatestVersion = ((Get-ChildItem "$Filename").Name).Trimstart("Firefox Setup ").TrimEnd(".exe")
				$URL = "https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US"
				Add-LogContent $LatestVersion
				Add-LogContent $URL
			</PrefetchScript>
			<URL></URL>
			<DownloadFileName>
				(Get-ChildItem "$TempDir\$FileName" |Select-Object -ExpandProperty BaseName)
			</DownloadFileName>
			<Version></Version>
			<FullVersion></FullVersion>
			<DownloadVersionCheck>
				$Version = ((get-Childitem $TempDir\$FileName).Name)
				$FileVersion = ((get-Childitem $TempDir\$FileName).Name)
				$FullVersion = (Get-ChildItem "$TempDir\$FileName" |Select-Object -ExpandProperty BaseName)
			</DownloadVersionCheck>
		</Download>
	</Downloads>
	<DeploymentTypes>
		<DeploymentType Name="DeploymentType1">
			<DeploymentTypeName>Firefox Enterprise x64 Silent Install</DeploymentTypeName>
			<InstallationType>Script</InstallationType>
			<CacheContent>False</CacheContent>
			<BranchCache>True</BranchCache>
			<ContentFallback>True</ContentFallback>
			<OnSlowNetwork>Download</OnSlowNetwork>
			<InstallProgram>$FileName -ms</InstallProgram>
			<UninstallCmd>`"%ProgramFiles%\Mozilla Firefox\uninstall\helper.exe`" -ms</UninstallCmd>
			<InstallationBehaviorType>InstallForSystem</InstallationBehaviorType>
			<LogonReqType>WhetherOrNotUserLoggedOn</LogonReqType>
			<UserInteractionMode>Hidden</UserInteractionMode>
			<EstRuntimeMins>5</EstRuntimeMins>
			<MaxRuntimeMins>20</MaxRuntimeMins>
			<RebootBehavior>BasedOnExitCode</RebootBehavior>
			<DetectionMethodType>Custom</DetectionMethodType>
			<CustomDetectionMethods>
				<DetectionClause>
					<DetectionClauseType>File</DetectionClauseType>
					<Name>firefox.exe</Name>
					<Path>%ProgramFiles%\Mozilla Firefox</Path>
					<PropertyType>Version</PropertyType>
					<ExpectedValue>$FullVersion</ExpectedValue>
					<ExpressionOperator>IsEquals</ExpressionOperator>
					<Value>True</Value>
					<Is64Bit>True</Is64Bit>
				</DetectionClause>
			</CustomDetectionMethods>
		</DeploymentType>
	</DeploymentTypes>
	<Distribution>
		<DistributeContent>True</DistributeContent>
	</Distribution>
	<Deployment>
		<DeploySoftware>True</DeploySoftware>
	</Deployment>
</ApplicationDef>

**Comment by asjimene** [comment]
Which Firefox version are you looking to package here? I have FirefoxESR and Firefox Dev edition recipes available at the moment. Taking the Firefox ESR recipe and replacing "FIREFOX_ESR" here:
`$Version = (ConvertFrom-JSON (Invoke-WebRequest -URI "https://product-details.mozilla.org/1.0/firefox_versions.json").Content).FIREFOX_ESR`
With the version that you want from [here](https://product-details.mozilla.org/1.0/firefox_versions.json) should get you whatever version you want to download and package.
Good luck!

**Comment by DavidMcSpadden** [comment]
Thank you for the reponse.
I did not see it back in December.
I will give it a shot.
Thanks.

**Comment by asjimene** [comment]
Ahh, you are welcome! Good luck!
