### ISSUE TITLE
Feature Request: Version comparison before Download

### ISSUE THREAD

**Issue by aimar115** [asjimene/CMPackager#24]
Hi

It would be wery useful if the script could compare versions before downloading the installer.
Some applications have versionnumbers in their download URL or website.

I think it could be made adding extra variable(line) in XML which result would be Version variable to compare with SCCM before downloading.

What do you think?

**Comment by asjimene** [comment]
This is definitely something I want to add in the future 😁

**Comment by asjimene** [comment]
Added in Commit: 84b1596e272fdcdcea0a97589c3578d573dac120
Will merge either tomorrow or Jan 1 :)

**Comment by asjimene** [comment]
Reopening this. Lots of funkiness during testing, so I'll need to rethink how I want to handle it.

**Comment by asjimene** [comment]
This feature has been added with Jetbrains Toolbox as an example.

Simply assign the version to the $Download.Version in the Prefetch Script for each download and that version will be checked against what exists in ConfigMgr to determine if the application actually needs to be downloaded.

**Comment by aimar115** [comment]
Thank You!
