### ISSUE TITLE
Firefox Recipe Detection Issue

### ISSUE THREAD

**Issue by DoubleM-DCDSB** [asjimene/CMPackager#28]
The Firefox MSI isn't a real MSI so you cannot detect it's installation based off the MSI product code.

See: [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1563501) and also [here.](https://bugzilla.mozilla.org/show_bug.cgi?id=1505436)

Changing the detection to ignore the MSI Product code and only detect version fixes this.

Looking into the recipe I notice it must auto add the product code when deploying from MSI since the MSI detection isn't in the recipe... can we remove this auto-added detection method or change the File version detection to automatically be OR instead of AND?

**Comment by asjimene** [comment]
You are correct, this is a bug I noticed as well... I'll need to see if the detection method can be modified afterwards
