### ISSUE TITLE
Google Chrome creation failing.

### ISSUE THREAD

**Issue by AnMon1** [asjimene/CMPackager#32]
Hi, 

After downloading your tool on feb 26th 2020, I found out that the script doesn't create Google Chrome's application. According to Powershell, it fails to find GoogleChrome’s version. 

It does download the msi, but then deletes it and fails. 

Thank you!

**Comment by asjimene** [comment]
Just tested this and it is working for me. I would check the temp folder during the script's run and ensure Google Chrome is actually being downloaded. You may have a firewall issue, also ensure you've opened IE at least once or downloads may not work properly!
