### ISSUE TITLE
Skipped Download Still Running ExtraCopyFunctions

### ISSUE THREAD

**Issue by ryanbley3** [asjimene/CMPackager#37]
When skipping a download with $Download.Version, extracopyfunctions should probably also be skipped unless I am missing something.

**Comment by ryanbley3** [comment]
Actually it wasn't the ExtraCopyFuctions, it was the download version check happening after the skip. I now understand that this section should be blank when assigning $download.version in prefetch.

**Comment by ryanbley3** [comment]
So $version and $download.version must be specified in prefetch, or else when moving the download to the content folder the folder named after version does not get created.

**Comment by asjimene** [comment]
Good to know, I'll see if I can get that straightened out. Thanks for the info!
