### ISSUE TITLE
Application Supersedence Attempts to Supersede Retired Applications

### ISSUE THREAD

**Issue by rjohnson06gh** [asjimene/CMPackager#40]
I've ran into an issue with some applications that have many versions where, when the recipe has supersedence configured for "true", that it will attempt to supersedence really old or retired applications.  For my case (Firefox ESR), we had 5 versions in SCCM with one in production and 4 superseded and retired.  When the newest version came out, it tried to supersede the first two applications, not the most recent.

In line 1390 of the CMPackager.ps1 (under the Invoke-ApplicationSupersedence function), would it make sense to exclude retired applications from the latest applications (Where-Object {$_.IsExpired -eq $False})? Or maybe even excluding apps that are already superseded (Where-Object {$_.IsSuperseded -eq $False})?  Maybe even just doing the "Select-Object -last 2" instead of "Select-Object -first 2" to account for the newly created app and the most recently deployed application?

**Comment by HeyZeus-Tech** [comment]
I hit a similar issue where supersedence is updating the previous release instead of the new release.
When trying to package 81.0.4044.138

```
Application Supersedence
Supersedence is True
Latest 2 apps = Google Chrome 81.0.4044.113 Google Chrome 81.0.4044.122
Old: Google Chrome 81.0.4044.113 New: Google Chrome 81.0.4044.122

```
