### ISSUE TITLE
Allow Full Customization of Content Path

### ISSUE THREAD

**Issue by asjimene** [asjimene/CMPackager#42]
Allow full configuration of content path, with variable support.
If I want to throw my files in $Manufacturer\Packages\Potato\$ApplicationName\$Version, that should be my choice darn it!

**Comment by n8felton** [comment]
Are you accepting PRs for this, or is this something you've already started working on?

**Comment by asjimene** [comment]
I have not started work on this yet, and would love a PR for it ☺

**Comment by bmkaiser** [comment]
@n8felton: Is this something you've begun working on?

**Comment by n8felton** [comment]
I have not yet. We're in the full swing of getting prepared for the start of Fall semester, along with all the "extra" that COVID-19 is throwing at us.

At this point, I probably won't have time to contribute to this until sometime this Fall/Winter

**Comment by bmkaiser** [comment]
I hear ya! I'm going to see if I can figure this out. Our content share doesn't follow the default structure and it would certainly be nice to have some flexibility.

**Comment by asjimene** [comment]
Feature added by @gavinliu0 Thanks so much!
