### ISSUE TITLE
Expand flexibility with MSI deployment types

### ISSUE THREAD

**Issue by rjohnson06gh** [asjimene/CMPackager#43]
I'm looking for expanded flexibility with the MSI deployment types such that the <InstallProgram> is respected for more that just MSI and CustomScript detection types.

Currently with MSI deployment types, the capability exists (from the Template.xml and looking through the "Special Arguments based on Detection Methods" in the Add-DeploymentType function) that a recipe can be an MSI type with MSI detection or CustomScript.  However, it does not allow for Custom detection (specially, with file detections).  I typically prefer to use this, and have used this over the MSI product code when the vendors don't use different codes for new versions.

Would it be possible to add the "Custom" detection to that Switch so that the <InstallProgram> is respected?

**Comment by asjimene** [comment]
You are correct, this is actually a bug at the moment, I will look at enabling this functionality in the future.

**Comment by jak552** [comment]
I'm just spinning this solution up at our shop and am finding that when using a custom detection method it creates the custom detection (in this case a file detection) but it also creates the MSI detection. Is this the same behavior described in this issue or possibly something different?

**Comment by asjimene** [comment]
Correct, this is the same bug.
