### ISSUE TITLE
Adobe Reader Recipe needs update

### ISSUE THREAD

**Issue by jak552** [asjimene/CMPackager#84]
#85 
```
<PrefetchScript>$latestVersion = (((Invoke-WebRequest https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/index.html) |Select-Object -ExpandProperty Links | where {$_.outertext -like "1* Planned Update, *"} |where {$_.href -like "continuous*"}|Sort-Object -Property innerText -Descending).innerText).Split(" ").replace(".","")[0]
<PrefetchScript>$latestVersion = (((Invoke-WebRequest https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/index.html) |Select-Object -ExpandProperty Links | where {$_.outertext -like "2* Planned Update, *"} |where {$_.href -like "continuous*"}|Sort-Object -Property innerText -Descending).innerText).Split(" ").replace(".","")[0]
```

I noticed the other day my reader app hadn't updated. I did do a quick test to ensure 20.X is the continuation of 19.X. Installed 19.X and initiated an update via the app itself which took me to 20.X.

Something people can easily update themselves but seems a good idea to update the base recipe as well.

If you ever start up a donation site (paypal or whatever) shoot me the details. Your script has saved me hundreds of hours. Least I can do is buy your next cup of coffee.

**Comment by fabdi00** [comment]
this is actually failing with the following error: you cannot call a method on a null-valued expression.

I have trying to get it fixed but no luck.

also, thanks for this amazing tool. much appreciated.

**Comment by fabdi00** [comment]
Ok I have figured it out, this is what I used to get it work: 

$latestVersion = invoke-webrequest -Uri https://adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/index.html -UseBasicParsing | select-object -ExpandProperty Links | select -ExpandProperty outerHTML
$pattern = "Planned"
$first = $html -match $pattern | Select-Object -First 1 | Select-String -Pattern "\d\d\.\d\d\d.\d\d\d\d\d"
$first = $first.Matches.Value
$latestVersion = $first.replace(".","")
$URL = "https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/$($latestVersion)/AcroRdrDC$($latestVersion)_en_US.exe"
