### ISSUE TITLE
Supersedence for out-of-order releases

### ISSUE THREAD

**Issue by theaquamarine** [asjimene/CMPackager#88]
Software that makes releases that aren't always in normal numerical order can currently end up with a higher release number superseded by a lower release number since supersedence always picks the most recently created application as the "old version", for example, [PowerShell releasing 7.0.4 after 7.1.1](https://github.com/PowerShell/PowerShell/releases) so 7.0.4 ends up superseding 7.1.1.
https://github.com/asjimene/CMPackager/blob/ae418693a5c725c83cbd176b456061e17736f683/CMPackager.ps1#L1618

The current system works fine in most situations and is great for software that doesn't have comparable version numbers for releases, but can't handle this at all - any thoughts? I can see two options
- an option (or changing the default) to only accept higher versions in `Invoke-VersionCheck`, possibly per-application
- and/or changing the sorting in `Invoke-ApplicationSupersedence` to use version number then date created and only superseding a lower version, also possibly per-application and possibly by default

**Comment by asjimene** [comment]
This is a very interesting _annoying_ issue, checking version numbers would be a task, there are so many different ways app versions are represented, it becomes tough to generalize a version check function. This is why the current version check only determines if the downloaded version is different from the existing versions in ConfigMgr. 

I think this might be better tackled on a per-app basis. I'm not sure of the PowerShell versioning, but it seems like they are working on 2 "branches", 7.0.x and 7.1.x, perhaps updating the recipe to only grab the 7.1.x releases would fix this issue.
